[package]
name = "crabipi"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
egui_extras = "0.33.0"
reqwest = { version = "0.12.24", features = ["json", "multipart"] }
rfd = "0.15.4"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
